In [3]:
def norm_feature(data):
    n_max = max(data)
    n_min = min(data)
    l_datta = len(data)

    for i in range(0, l_datta):
        data[i]=(data[i]-n_min)/(n_max-n_min)
        
    return data

In [5]:
data = [10, 25, 25, 30, 50]

n_data = norm_feature(data)
n_data

[0.0, 0.375, 0.375, 0.5, 1.0]

In [6]:
import numpy as np 
from sklearn.preprocessing import MinMaxScaler

In [19]:
data = [
    [100, 0.01],
    [8, 0.05],
    [50, 0.005]
    
]

np_data = np.asanyarray(data)
mm_scaler = MinMaxScaler()
mm_data = mm_scaler.fit_transform(data)
mm_data

array([[1.        , 0.11111111],
       [0.        , 1.        ],
       [0.45652174, 0.        ]])

In [26]:
from statistics import mean, pstdev, stdev


def std_feature(data):
    mean_data = mean(data)
    std_data = stdev(data)
    baris_data = len(data)
    kolom_data = len(data[0])

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            data[i][j] = (data[i][j] - mean(data[:,j])) / pstdev((data[:,j]))

        return data

In [28]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]

data = np.asanyarray(data)

std_data = std_feature(data)
std_data

TypeError: can't convert type 'ndarray' to numerator/denominator

In [27]:
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler()

std_data = ss_scaler.fit_transform(data)
std_data

array([[ 1.26398112, -1.16389967],
       [-1.06174414,  0.12639634],
       [ 0.        , -1.05856939],
       [ 0.96062565,  0.65304778],
       [-1.16286263,  1.44302493]])

In [31]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

oe = [
    ['polinema'],
    ['pens'],
    ['pnj'],
    ['pnp'],
    ['polban']
]

ord_oe = OrdinalEncoder().fit_transform(oe)
ohe_oe = OneHotEncoder().fit_transform(oe)
ohe_oe.toarray()

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [32]:
corpus = [
        'the house had a tiny little mouse',
        'the cat saw the mouse',
        'the mouse ran away from the house',
        'the cat finally ate the mouse',
        'the end of the mouse story'
]

In [35]:
sentence =  'the house had a tiny little mouse. the cat saw the mouse.the mouse ran away from the house'

stc_split = sentence.split('.')
stc_split

['the house had a tiny little mouse',
 ' the cat saw the mouse',
 'the mouse ran away from the house']

In [39]:
from unittest import result
from sklearn.feature_extraction.text import TfidfTransformer

vect = TfidfTransformer(stop_words='english')
result= vect.fit_transform(corpus)
print(vect.get_features_names())
print(result.toarray()[0])
print(result.todense())

TypeError: __init__() got an unexpected keyword argument 'stop_words'